added_as_delegate:
 print: added_as_delegate
 inverse: removed_as_delegate
 human_readable: Added as a delegate
 template: _delegate_change.html.erb
removed_as_delegate:
 print: removed_as_delegate
 inverse: added_as_delegate
 human_readable: Removed as a delegate
 template: _delegate_change.html.erb
added_as_editor:
 print: added_as_editor
 inverse: removed_as_editor
 human_readable: Added as an editor
 template: _editor_change.html.erb
removed_as_editor:
 print: removed_as_editor
 inverse: added_as_editor
 human_readable: Removed as an editor
 template: _editor_change.html.erb
added_to_group:
 print: added_to_group
 inverse: removed_from_group
 human_readable: Added to a group
 template: _group_change.html.erb
removed_from_group:
 print: removed_from_group
 inverse: added_to_group
 human_readable: Removed from a group
 template: _group_change.html.erb
